using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Xml.Linq;

namespace WersjonowanieDanych
{
    public class XEL_component
    {
        private static readonly XNamespace aw = "urn:hl7-org:v3";

        private XElement component;

        public XEL_component()
        {
            component = new XElement(aw + "component",
            #region component
                new XAttribute("typeCode", "COMP"),
                new XAttribute("contextConductionInd", "true"),
                new XElement(aw + "templateId",
                    new XAttribute("root", "2.16.840.1.113883.3.4424.13.10.2.60")),
                new XElement(aw + "structuredBody",
                    new XAttribute("classCode", "DOCBODY"),
                    new XAttribute("moodCode", "EVN"),
                    new XElement(aw + "component",
                        new XElement(aw + "section",
                            new XElement(aw + "templateId",
                                new XAttribute("root", "2.16.840.1.113883.3.4424.13.10.3.56")),
                                new XElement(aw + "text",
                                    new XElement(aw + "list",
                                        new XElement(aw + "caption", "Pobyty na oddziałach:"),
                                        new XElement(aw + "item",
                                            new XAttribute("ID", "ENC_1"), "01.09.2014 - 03.09.2014 Oddział kardiologii"),
                                        new XElement(aw + "item",
                                            new XAttribute("ID", "ENC_2"), "03.09.2014 - 06.09.2014 Oddział neurologii"))),
                            new XElement(aw + "entry",
                                new XElement(aw + "encounter",
                                    new XAttribute("newclassCode", "ENC"),
                                    new XAttribute("moodCode", "EVN"),
                                    new XElement(aw + "templateId",
                                        new XAttribute("root", "2.16.840.1.113883.3.4424.13.10.4.50")),
                                    new XElement(aw + "code",
                                        new XAttribute("code", "4100"),
                                        new XAttribute("codeSystem", "2.16.840.1.113883.3.4424.11.2.4"),
                                        new XAttribute("displayName", "Oddział kardiologiczny")),
                                    new XElement(aw + "text",
                                        new XElement(aw + "reference",
                                            new XAttribute("value", "#ENC_1"))),
                                    new XElement(aw + "effectiveTime",
                                        new XElement(aw + "low",
                                            new XAttribute("value", "20140901")),
                                        new XElement(aw + "high",
                                            new XAttribute("value", "20140903"))))),
                            new XElement(aw + "entry",
                                new XElement(aw + "encounter",
                                    new XAttribute("classCode", "ENC"),
                                    new XAttribute("moodCode", "EVN"),
                                    new XElement(aw + "templateId",
                                        new XAttribute("root", "2.16.840.1.113883.3.4424.13.10.4.50")),
                                    new XElement(aw + "code",
                                        new XAttribute("code", "4220"),
                                        new XAttribute("codeSystem", "2.16.840.1.113883.3.4424.11.2.4"),
                                        new XAttribute("displayName", "Oddział neurologiczny")),
                                    new XElement(aw + "text",
                                        new XElement(aw + "reference",
                                            new XAttribute("value", "#ENC_2"))),
                                    new XElement(aw + "effectiveTime",
                                        new XElement(aw + "low",
                                            new XAttribute("value", "20140903")),
                                        new XElement(aw + "high",
                                            new XAttribute("value", "20140906"))))))),
                    new XElement(aw + "component",
                        new XElement(aw + "section",
                            new XElement(aw + "templateId",
                                new XAttribute("root", "2.16.840.1.113883.3.4424.13.10.3.1")),
                            new XElement(aw + "code",
                                new XAttribute("code", "29548-5"),
                                new XAttribute("codeSystem", "2.16.840.1.113883.6.1"),
                                new XAttribute("codeSystemName", "LOINC"),
                                new XAttribute("displayName", "Diagnosis")),
                            new XElement(aw + "title", "Rozpoznania"),
                            new XElement(aw + "text",
                                new XElement(aw + "table",
                                    new XElement(aw + "tbody",
                                        new XElement(aw + "tr",
                                            new XAttribute("ID", "DIAG_1"),
                                            new XElement(aw + "td", "Udar niedokrwienny mózgu"),
                                            new XElement(aw + "td", "I63.3")),
                                        new XElement(aw + "tr",
                                            new XAttribute("ID", "DIAG_2"),
                                            new XElement(aw + "td", "Nadciśnienie tętnicze"),
                                            new XElement(aw + "td", "I10"))))),
                            new XElement(aw + "entry",
                                new XElement(aw + "templateId",
                                    new XAttribute("root", "2.16.840.1.113883.3.4424.13.10.4.1")),
                                new XElement(aw + "organizer",
                                    new XAttribute("classCode", "BATTERY"),
                                    new XAttribute("moodCode", "EVN"),
                                    new XElement(aw + "code",
                                        new XAttribute("code", "8319008"),
                                        new XAttribute("codeSystem", "2.16.840.1.113883.6.96"),
                                        new XAttribute("codeSystemName", "SNOMED CT"),
                                        new XAttribute("displayName", "Principal diagnosis")),
                                    new XElement(aw + "statusCode",
                                        new XAttribute("code", "completed")),
                                    new XElement(aw + "component",
                                        new XElement(aw + "observation",
                                            new XAttribute("classCode", "OBS"),
                                            new XAttribute("moodCode", "EVN"),
                                            new XElement(aw + "code",
                                                new XAttribute("code", "I63.3"),
                                                new XAttribute("codeSystem", "2.16.840.1.113883.6.3"),
                                                new XAttribute("codeSystemName", "icd10"),
                                                new XAttribute("displayName", "Zawał mózgu wywołany przez zakrzep tętnic mózgowych"),
                                                new XElement(aw + "text",
                                                    new XElement(aw + "reference",
                                                        new XAttribute("value", "#DIAG_1")))))))),
                            new XElement(aw + "entry",
                                new XElement(aw + "templateId",
                                    new XAttribute("root", "2.16.840.1.113883.3.4424.13.10.4.2")),
                                new XElement(aw + "organizer",
                                    new XAttribute("classCode", "BATTERY"),
                                    new XAttribute("moodCode", "EVN"),
                                    new XElement(aw + "code",
                                        new XAttribute("code", "85097005"),
                                        new XAttribute("codeSystem", "2.16.840.1.113883.6.96"),
                                        new XAttribute("codeSystemName", "SNOMED CT"),
                                        new XAttribute("displayName", "Secondary diagnosis")),
                                    new XElement(aw + "statusCode",
                                        new XAttribute("code", "completed")),
                                    new XElement(aw + "component",
                                        new XElement(aw + "observation",
                                            new XAttribute("classCode", "OBS"),
                                            new XAttribute("moodCode", "EVN"),
                                            new XElement(aw + "code",
                                                new XAttribute("code", "I10"),
                                                new XAttribute("codeSystem", "2.16.840.1.113883.6.3"),
                                                new XAttribute("codeSystemName", "icd10"),
                                                new XAttribute("displayName", "Samoistne (pierwotne) nadciśnienie")),
                                            new XElement(aw + "text",
                                                new XElement(aw + "reference",
                                                    new XAttribute("value", "#DIAG_2"))))))))),
                    new XElement(aw + "component",
                        new XElement(aw + "section",
                            new XElement(aw + "templateId",
                                new XAttribute("root", "2.16.840.1.113883.3.4424.13.10.3.35")),
                            new XElement(aw + "code",
                                new XAttribute("code", "30954 -2"),
                                new XAttribute("codeSystem", "2.16.840.1.113883.6.1"),
                                new XAttribute("codeSystemName", "LOINC"),
                                new XAttribute("displayName", "Relevant diagnostic tests/laboratory data")),
                            new XElement(aw + "title", "Wyniki badań"),
                                new XElement(aw + "text",
                                    new XElement(aw + "table",
                                        new XElement(aw + "thead",
                                            new XElement(aw + "tr",
                                                new XElement(aw + "th", "Nazwa badania"),
                                                new XElement(aw + "th", "Wynik badania"),
                                                new XElement(aw + "th", "Zakres referencyjny"))),
                                        new XElement(aw + "tbody",
                                            new XElement(aw + "tr",
                                                new XAttribute("ID", "OBS_1"),
                                                new XElement(aw + "td", "Morfologia krwi obwodowej",
                                                    new XAttribute("colspan", "3"),
                                                    new XAttribute("styleCode", "Bold"))),
                                            new XElement(aw + "tr",
                                                new XAttribute("ID", "OBS_2"),
                                                new XElement(aw + "td", "WBC Krwinki białe"),
                                                new XElement(aw + "td", "8,3 K/" + '\u00B5' + "l"),
                                                new XElement(aw + "td", "4,0 - 10,0")),
                                            new XElement(aw + "tr",
                                                new XAttribute("ID", "OBS_3"),
                                                new XElement(aw + "td", "RBC Krwinki czerwone"),
                                                new XElement(aw + "td", "3,35 M/" + '\u00B5' + "l"),
                                                new XElement(aw + "td", "4,0 - 5,0")),
                                            new XElement(aw + "tr",
                                                new XAttribute("ID", "OBS_4"),
                                                new XElement(aw + "td", "PLT Płytki krwi"),
                                                new XElement(aw + "td", "331,0 K/" + '\u00B5' + "l"),
                                                new XElement(aw + "td", "140,0 - 400,0")),
                                            new XElement(aw + "tr",
                                                new XAttribute("ID", "OBS_5"),
                                                new XElement(aw + "td", "HGB Hemoglobina"),
                                                new XElement(aw + "td", "7,8 g/dl"),
                                                new XElement(aw + "td", "12,0 - 16,0")),
                                            new XElement(aw + "tr",
                                                new XAttribute("ID", "OBS_6"),
                                                new XElement(aw + "td", "HCT Hematokryt"),
                                                new XElement(aw + "td", "27,1 %"),
                                                new XElement(aw + "td", "37,0 - 47,0")),
                                            new XElement(aw + "tr",
                                                new XAttribute("ID", "OBS_7"),
                                                new XElement(aw + "td", "MCHC"),
                                                new XElement(aw + "td", "28,8 g/dl"),
                                                new XElement(aw + "td", "31,0 - 36,0")),
                                            new XElement(aw + "tr",
                                                new XAttribute("ID", "OBS_8"),
                                                new XElement(aw + "td", "MCV"),
                                                new XElement(aw + "td", "80,9 fl"),
                                                new XElement(aw + "td", "80,0 - 96,0")),
                                            new XElement(aw + "tr",
                                                new XAttribute("ID", "OBS_9"),
                                                new XElement(aw + "td", "MCH"),
                                                new XElement(aw + "td", "23 pg"),
                                                new XElement(aw + "td", "26,0 - 32,0"))))))),
                    new XElement(aw + "component",
                        new XElement(aw + "section",
                            new XElement(aw + "templateId",
                                new XAttribute("root", "2.16.840.1.113883.3.4424.13.10.3.36")),
                            new XElement(aw + "code",
                                new XAttribute("code", "55753 -8"),
                                new XAttribute("codeSystem", "2.16.840.1.113883.6.1"),
                                new XAttribute("codeSystemName", "LOINC"),
                                new XAttribute("displayName", "Treatment information")),
                            new XElement(aw + "title", "Leczenie"),
                            new XElement(aw + "text",
                                new XElement(aw + "paragraph", "Farmakoterapia i rehabilitacja ruchowa.")))),
                    new XElement(aw + "component",
                        new XElement(aw + "section",
                            new XElement(aw + "templateId",
                                new XAttribute("root", "2.16.840.1.113883.3.4424.13.10.3.37")),
                            new XElement(aw + "code",
                                new XAttribute("code", "11493 -4"),
                                new XAttribute("codeSystem", "2.16.840.1.113883.6.1"),
                                new XAttribute("codeSystemName", "LOINC"),
                                new XAttribute("displayName", "Hospital discharge studies summary Narrative")),
                            new XElement(aw + "title", "Epikryza"),
                            new XElement(aw + "text",
                                new XElement(aw + "paragraph", "52 - letni pacjent przyjęty do Kliniki z powodu nagłego wystąpienia osłabienia siły mięśniowej lewych kończyn." +
                                "W badaniu neurologicznym przy przyjęciu - centralny niedowład n. VII lewego, niedoczulica lewej połowy twarzy, średniego stopnia niedowład lewej kończyny górnej, " +
                                "wzmożone napięcie mięśniowe kk.górnych typu pozapiramidowego, drżenie w obrębie prawej kończyny górnej, średniego stopnia niedowład lewej kończyny dolnej, " +
                                "wzmożone napięcie mięśniowe kk. dolnych typu pozapiramidowego, dodatni objaw Babińskiego po stronie lewej. W wywiadzie -nadciśnienie tętnicze, zespół parkinsonowski, " +
                                "łagodny przerost gruczołu krokowego, stan po cholecystektomii.W badaniu tomografii komputerowej głowy przy przyjęciu - " +
                                "wieloogniskowe naczyniopochodne uszkodzenie mózgu oraz zanik korowo-podkorowy mózgu.W badaniu USG tt. domózgowych - " +
                                "po stronie lewej zwężenie początkowego odcinka tętnicy szyjnej wewnętrznej o ok. 40 - 60 %, po stronie prawej stopień zwężenia trudny do oceny ze względu na cienie akustyczne od zwapnień - " +
                                "bez zaburzeń hemodynamiki przepływu krwi. W badaniu przezczaszkowym USG tt.mózgowych - bez zaburzeń przepływu. " +
                                "Ze względu na stwierdzane podczas ostatniej hospitalizacji na Oddziale Kardiologii poszerzenie aorty wstępującej w obrazie echokardiograficznym wykonano badanie kontrolne - " +
                                "obraz serca i naczyń porównywany w badaniem poprzednim.W trakcie hospitalizacji stosowano leczenie przeciwobrzękowe, przeciwpłytkowe, " +
                                "przeciwnadciśnieniowe, hipolipemizujące oraz rehabilitację ruchową uzyskując dużą poprawę stanu neurologicznego w zakresie sprawności lewych kończyn.Ze względu na objawy pozapiramidowe włączono " +
                                "Madopar w dawce 250mg / dobę w czterech dawkach podzielonych. Chorego w stanie ogólnym dobrym wypisano do domu.W badaniu neurologicznym w dniu wypisu - dyskretny niedowład lewej kończyny górnej, " +
                                "wzmożone napięcie mięśniowe kk.górnych typu pozapiramidowego - o mniejszym nasileniu, dyskretny niedowład lewej kończyny dolnej, wmożone napięcie mięśniowe kk.dolnych typu pozapiramidowego -" +
                                " o mniejszym nasileniu, bez objawów patologicznych.")))),
                    new XElement(aw + "component",
                        new XElement(aw + "section",
                            new XElement(aw + "templateId",
                                new XAttribute("root", "2.16.840.1.113883.3.4424.13.10.3.32")),
                            new XElement(aw + "code",
                                new XAttribute("code", "57828 -6"),
                                new XAttribute("codeSystem", "2.16.840.1.113883.6.1"),
                                new XAttribute("codeSystemName", "LOINC"),
                                new XAttribute("displayName", "Prescriptions /Prescription list")),
                            new XElement(aw + "title", "Zalecenia"),
                            new XElement(aw + "text",
                                new XElement(aw + "list",
                                    new XElement(aw + "item", "Polocard 150 mg, 2 x 1 tabl.",
                                        new XAttribute("ID", "SBADM_1")),
                                    new XElement(aw + "item", "Atoris 20 mg, 2 x 1 tabl. (rano i wieczorem)",
                                        new XAttribute("ID", "SBADM_2")),
                                    new XElement(aw + "item", "Pić przynajmniej 2 litry wody dziennie"))),
                            new XElement(aw + "entry",
                                new XElement(aw + "templateId",
                                    new XAttribute("root", "2.16.840.1.113883.3.4424.13.10.4.22")),
                                new XElement(aw + "substanceAdministration",
                                    new XAttribute("classCode", "SBADM"),
                                    new XAttribute("moodCode", "RQO"),
                                    new XElement(aw + "text",
                                        new XElement(aw + "reference",
                                            new XAttribute("value", "#SBADM_1"))),
                                    new XElement(aw + "consumable",
                                        new XElement(aw + "manufacturedProduct",
                                            new XElement(aw + "templateId",
                                                new XAttribute("root", "2.16.840.1.113883.3.4424.13.10.4.21")),
                                            new XElement(aw + "manufacturedLabeledDrug",
                                                new XElement(aw + "code",
                                                    new XAttribute("code", "100997"),
                                                    new XAttribute("codeSystem", "2.16.840.1.113883.3.4424.6.1"),
                                                    new XAttribute("displayName", "Polocard 150 mg tabletki"))))))),
                            new XElement(aw + "entry",
                                new XElement(aw + "templateId",
                                    new XAttribute("root", "2.16.840.1.113883.3.4424.13.10.4.22")),
                                new XElement(aw + "substanceAdministration",
                                    new XAttribute("classCode", "SBADM"),
                                    new XAttribute("moodCode", "RQO"),
                                    new XElement(aw + "text",
                                        new XElement(aw + "reference",
                                            new XAttribute("value", "#SBADM_2"))),
                                    new XElement(aw + "consumable",
                                        new XElement(aw + "manufacturedProduct",
                                            new XElement(aw + "templateId",
                                                new XAttribute("root", "2.16.840.1.113883.3.4424.13.10.4.21")),
                                            new XElement(aw + "manufacturedLabeledDrug",
                                                new XElement(aw + "code",
                                                    new XAttribute("code", "100996"),
                                                    new XAttribute("codeSystem", "2.16.840.1.113883.3.4424.6.1"),
                                                    new XAttribute("displayName", "Atoris 20 mg tabletki")))))))))));
            #endregion
        }
        public XElement ZrotWartosci()
        {
            return component;
        }
    }
}